name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${SHORT_SHA}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./BlabberCord
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/blabber-cord:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/blabber-cord:${SHORT_SHA}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Update Docker Hub Description
        if: github.ref == 'refs/heads/main'
        run: sudo apt-get install jq && chmod +x ./update_dockerhub_description.sh && ./update_dockerhub_description.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} ${{ secrets.DOCKERHUB_USERNAME }}/blabber-cord ./README.md
